/*
Copyright © 2025 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/zikrullah79/scovi/service"
)

// generateCmd represents the generate command
var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a coverage report",
	Long: `This command parses a coverage file and generates a report.
It reads the specified file, processes the coverage data, and outputs a report.
The file should be in the format generated by 'go test -coverprofile=coverage.out'.`,
	Run: func(cmd *cobra.Command, args []string) {
		extractor := service.NewParseService()
		parser := service.NewParserService()

		// get the file flag from the command line arguments
		file, err := cmd.Flags().GetString("file")
		if err != nil {
			fmt.Println("Error getting file flag:", err)
			return
		}
		// if file is empty, print an error message and return
		// this is to ensure that the user provides a file to process
		if file == "" {
			fmt.Println("No file provided. Use -f or --file to specify a file.")
			return
		}

		b, err := extractor.ExtractCoverageFile(file)
		if err != nil {
			fmt.Println("Error getting file flag:", err)
			return
		}
		err = parser.ParseHtmlFile(extractor.SummarizeCoverage(b), "")
		if err != nil {
			fmt.Println("Error parsing HTML file:", err)
			return
		}
		fmt.Println("Coverage report generated successfully.")
		fmt.Println("You can find the report in the current directory as 'coverage_report.html'.")
		fmt.Println("You can open it in your web browser to view the coverage report.")
		fmt.Println("Thank you for using the coverage report generator!")

	},
}

func init() {
	rootCmd.AddCommand(generateCmd)

	// This allows the user to specify a file to process when running the command.
	generateCmd.Flags().StringP("file", "f", "", "File to process")

}
