/*
Copyright © 2025 Zikrullah Aliwainda zikrullahaliwaindah@gmail.com
*/
package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "app",
	Short: "Generate a coverage report",
	Long: `This command parses a coverage file and generates a report.
It reads the specified file, processes the coverage data, and outputs a report.
The file should be in the format generated by 'go test -coverprofile=coverage.out'.`,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
